schema_version = "1.0.0"
id = "HardsurfaceGameAssetToolkit"
version = "2024, 7"
name = "HardsurfaceGameAssetToolkit"
tagline = "用于自定义流程游戏资产制作的blender插件"
maintainer = "LiuYang"
type = "add-on"


# Optional link to documentation, support, source files, etc
website = "https://github.com/LiuYangArt/HardsurfaceGameAssetToolkit"


tags = ["Scene", "3D View"]
blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
